trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: maven:3.6.1-jdk-8-slim

steps:
- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: settings.xml

- bash: |
   echo $HOME
   echo "##vso[task.setvariable variable=Docker.Home]$HOME"

- task: CopyFiles@2
  displayName: 'Copy settings.xml'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: settings.xml
    TargetFolder: '$(Docker.Home)/.m2/'

- task: Maven@3
  displayName: 'Maven deploy'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy -Pazure'
    publishJUnitResults: false
    mavenAuthenticateFeed: false
